# Generated by Django 4.2 on 2024-04-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Имя заказчика'),
        ),
        migrations.AlterField(
            model_name='executorprofile',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Имя исполнителя'),
        ),
    ]
