# Generated by Django 4.2 on 2024-04-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customerprofile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executorprofile',
            name='profession',
            field=models.CharField(default=1, max_length=200, verbose_name='Профессия'),
            preserve_default=False,
        ),
    ]
